### PR TITLE
[incubator-kie-issues-1084] User eager fetching in ProcessDefinitionEntity to avoid transaction errors

### LINKED ISSUE #1084: Application using data-index persistence fails or hangs with debug level logging enabled
Using the [compact architecture example](https://github.com/apache/incubator-kie-kogito-examples/tree/main/kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus), the application either fails or hangs after enabling debug level logging in `application.properties`:
```
quarkus.log.level=DEBUG
```
The following errors can be seen in the console:
```
10:53:35,126 DEBUG [org.hibernate.engine.jdbc.spi.SqlExceptionHelper:134] (pool-5-thread-1) could not prepare statement [select n1_0.process_id,n1_0.process_version,n1_0.id,n1_0.name,n1_0.type,n1_0.unique_id from definitions_nodes n1_0 where (n1_0.process_id,n1_0.process_version) in ((?,?))]: java.sql.SQLException: Enlisted connection used without active transaction
	at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:398)
	at io.agroal.pool.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:657)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:150)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:177)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:152)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.lambda$list$0(JdbcSelectExecutorStandardImpl.java:102)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:226)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:163)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:254)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:134)
	at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:19)
	at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:66)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:178)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:361)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93)
	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
	at org.hibernate.loader.ast.internal.CollectionLoaderSingleKey.load(CollectionLoaderSingleKey.java:114)
	at org.hibernate.loader.ast.internal.CollectionBatchLoaderInPredicate.load(CollectionBatchLoaderInPredicate.java:120)
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:680)
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1702)
	at org.hibernate.collection.spi.AbstractPersistentCollection.lambda$initialize$3(AbstractPersistentCollection.java:617)
	at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265)
	at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:615)
	at org.hibernate.collection.spi.AbstractPersistentCollection.read(AbstractPersistentCollection.java:136)
	at org.hibernate.collection.spi.PersistentBag.toString(PersistentBag.java:589)
	at java.base/java.lang.StringConcatHelper.stringOf(StringConcatHelper.java:453)
	at org.kie.kogito.index.jpa.model.ProcessDefinitionEntity.toString(ProcessDefinitionEntity.java:204)

```

### PR DESCRIPTION
**Pull request by martinweiler**
Fixes https://github.com/apache/incubator-kie-issues/issues/1084

### CODE REVIEW

**Review by elguardian — APPROVED** [review]

**Comment by elguardian** [comment]
I am not sure this is the best approach.
@fjtirado This happens when toString is invoked as it requires to load those lazy fields. If you have any other suggestion plz. go ahead.

**Comment by fjtirado** [comment]
@martinweiler I think removing the three collections from toString method will be enough. Lets keep loading of collections lazy. 
See https://struberg.wordpress.com/2016/10/15/tostring-equals-and-hashcode-in-jpa-entities/ for more rationale on that

File: data-index/data-index-storage/data-index-storage-jpa-common/src/main/java/org/kie/kogito/index/jpa/model/ProcessDefinitionEntity.java [hunk 1]
```diff
@@ -53,14 +54,14 @@ public class ProcessDefinitionEntity extends AbstractEntity {
     private String type;
     private byte[] source;
 
-    @ElementCollection
+    @ElementCollection(fetch = FetchType.EAGER)
```
Comment (fjtirado) [inline data-index/data-index-storage/data-index-storage-jpa-common/src/main/java/org/kie/kogito/index/jpa/model/ProcessDefinitionEntity.java]: I suggess to keep FetchType lazy

File: data-index/data-index-storage/data-index-storage-jpa-common/src/main/java/org/kie/kogito/index/jpa/model/ProcessDefinitionEntity.java [hunk 2]
```diff
@@ -208,7 +209,6 @@ public String toString() {
                 ", roles=" + roles +
                 ", addons=" + addons +
                 ", endpoint='" + endpoint + '\'' +
-                ", nodes='" + nodes + '\'' +
```
Comment (fjtirado) [inline data-index/data-index-storage/data-index-storage-jpa-common/src/main/java/org/kie/kogito/index/jpa/model/ProcessDefinitionEntity.java:211]: I think removing roles and addons from toString will do the trick
Im wondering if to string should just print the id and the version (the composite key) of the process definition to avoid further problem. That will be enough for logging

Comment (martinweiler) [reply data-index/data-index-storage/data-index-storage-jpa-common/src/main/java/org/kie/kogito/index/jpa/model/ProcessDefinitionEntity.java:211]: @fjtirado ok, let's just remove the fields that are lazy loaded from the toString method

**Review by pefernan — APPROVED** [review]
