### PR TITLE
kie-issues#1801: Fix ClassNotFoundException when Registering classes for Reflection

### LINKED ISSUE #1801: Fix Warnings on RegisterForReflectionBuildStep due to `java.lang.ClassNotFoundException`
After the quarkus `3.15.3` some warnings appeared in the build logs when during the `RegisterForReflectionBuildStep`. The affected classes are referenced in [ReflectionConfiguration.java](https://github.com/apache/incubator-kie-kogito-apps/blob/main/jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/reflection/ReflectionConfiguration.java#L32) and where deleted or moved to other packages in older PR's.

```
[WARNING] [io.quarkus.deployment.steps.RegisterForReflectionBuildStep] Failed to load Class org.kie.kogito.jobs.service.job.model.ScheduledJobAdapter$ProcessPayload
java.lang.ClassNotFoundException: org.kie.kogito.jobs.service.job.model.ScheduledJobAdapter$ProcessPayload
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:565)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:513)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:565)
    at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass (QuarkusClassLoader.java:513)
    at java.lang.Class.forName0 (Native Method)
    at java.lang.Class.forName (Class.java:467)
    at io.quarkus.deployment.steps.RegisterForReflectionBuildStep.registerClass (RegisterForReflectionBuildStep.java:132)
    at io.quarkus.deployment.steps.RegisterForReflectionBuildStep.build (RegisterForReflectionBuildStep.java:94)
    at java.lang.invoke.MethodHandle.invokeWithArguments (MethodHandle.java:732)
    at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:856)
    at io.quarkus.builder.BuildContext.run (BuildContext.java:256)
    at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith (EnhancedQueueExecutor.java:2516)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2495)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1521)
    at java.lang.Thread.run (Thread.java:840)
    at org.jboss.threads.JBossThread.run (JBossThread.java:483)
```

### PR DESCRIPTION
**Pull request by pefernan**
Closes https://github.com/apache/incubator-kie-issues/issues/1801

This PR tries to fix some unexpected warnings while building some apps when trying to Register some classes for the native images.

Main issue is that some of those classes where either deleted or moved to different package. To make this configuration a bit stronger I changed the annotation config to use the `targets` param which expects a Class[] instead of the `classNames`  which is a String[] and somehow was lead us to this issue after some classes got removed or refactored. Next time we'll be able to detect the problem earlier.

Ensemble:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3839
https://github.com/apache/incubator-kie-kogito-apps/pull/2187

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](https://github.com/apache/incubator-kie-kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-apps|kogito-examples] native-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

<details>
<summary>
Quarkus-3 PR check is failing ... what to do ?
</summary>
The Quarkus 3 check is applying patches from the `.ci/environments/quarkus-3/patches`.

The first patch, called `0001_before_sh.patch`, is generated from Openrewrite `.ci/environments/quarkus-3/quarkus3.yml` recipe. The patch is created to speed up the check. But it may be that some changes in the PR broke this patch.  
No panic, there is an easy way to regenerate it. You just need to comment on the PR:
```
jenkins rewrite quarkus-3
```
and it should, after some minutes (~20/30min) apply a commit on the PR with the patch regenerated.

Other patches were generated manually. If any of it fails, you will need to manually update it... and push your changes.
</details>

### CODE REVIEW

File: jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/reflection/ReflectionConfiguration.java [hunk 1]
```diff
@@ -18,42 +18,71 @@
...
-                "org.kie.kogito.jobs.service.api.recipient.sink.SinkRecipientJsonPayloadData",
-                "org.kie.kogito.jobs.service.api.Schedule",
-                "org.kie.kogito.jobs.service.api.schedule.timer.TimerSchedule",
-                "org.kie.kogito.jobs.service.api.schedule.cron.CronSchedule",
-                "org.kie.kogito.jobs.service.api.event.JobCloudEvent",
-                "org.kie.kogito.jobs.service.api.event.CreateJobEvent",
-                "org.kie.kogito.jobs.service.api.event.DeleteJobEvent",
-                "org.kie.kogito.jobs.service.resource.error.ErrorResponse"
+        targets = {
+                SpecVersionSerializer.class,
```
Comment (pefernan) [inline jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/reflection/ReflectionConfiguration.java:56]: @wmedvede I see we have this `SpecVersionSerializer` & `SpecVersionDeserializer` classes declared in two differnt packages, and both look pretty much the same, do you think we can unify them?

**Review by martinweiler — APPROVED** [review]
Nice work @pefernan

**Review by baldimir — APPROVED** [review]

**Review by yesamer — APPROVED** [review]

**Review by gitgabrio — APPROVED** [review]

File: jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/reflection/ReflectionConfiguration.java (hunk 1 above)
Comment (wmedvede) [reply jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/reflection/ReflectionConfiguration.java:56]: @pefernan yes, this is far from perfect, as you mentioned, this class is kind of duplicated in:
`jobs-service-api` and `kogito-events-core` but there is a rational (not perfect) behind that.

The `jobs-service-api` was intended to be an API decoupled from the other modules. On the other hand, in `kogito-events-core`, apart from the SpecVersionSerializer, we have classes that are specific to the business process events, etc.

So, to introduce a dependency jobs-service-api  --> kogito-events-core, is not good. In the opposite direction, not good too. Finally, IDK if we have a third "neutral" module where to add them, in a way that it don't introduces unwanted deps into the jobs-service-api.

Finally, considering that these classes are very basic, I think we can live with them.

**Review by wmedvede — APPROVED** [review]
