### PR TITLE
Fix kie-issues#1982: Add an optional property to add a custom UI to Jobs Service

### LINKED ISSUE #1982: Integrate the jobs-service-webapp in the jobs-service image
Integrate the webapp from kie-tools created in the task below, in the jobs-service image:

- https://github.com/apache/incubator-kie-tools/issues/2545

**Note:** this reopens https://github.com/apache/incubator-kie-kogito-images/issues/1794 after the branch has been archived

### PR DESCRIPTION
**Pull request by kumaradityaraj**
## 🚀 Integrating Jobs Service Webapp  
📌 Part of [apache/incubator-kie-issues#1982](https://github.com/apache/incubator-kie-issues/issues/1982)

---

This PR lays the groundwork for **integrating the Jobs Service Webapp** into the Kogito Apps ecosystem - enabling a consistent and modular approach to managing UI components across services.

It mirrors the successful integration strategy used for the **Data Index Webapp**  
🔗 Reference: [PR #2232](https://github.com/apache/incubator-kie-kogito-apps/pull/2232) and [PR #2234](https://github.com/apache/incubator-kie-kogito-apps/pull/2234)

---

### ✅ Highlights of This PR

- 🛠️ Adds all necessary structure and configuration to support the Jobs Service UI
- 🔄 Ensures seamless compatibility with the current build and deployment pipelines
- 📦 Follows the modular design standards used across other Kogito webapps

---

This PR is a **foundational step** toward completing the webapp integration outlined in [kie-issues#1982](https://github.com/apache/incubator-kie-issues/issues/1982).  
Your review and feedback are most welcome! 🙌

### CODE REVIEW

**Comment by kumaradityaraj** [comment]
@fantonangeli @ricardozanini @wmedvede Please review this PR. Thank you.

**Comment by kie-ci3** [comment]
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-apps -u https://github.com/apache/incubator-kie-kogito-apps/pull/2249 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/display/redirect

**Test results:**
- PASSED: 1665
- FAILED: 19

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.index.inmemory/KogitoDevServiceTest/testDataIndexDevService/">org.kie.kogito.index.inmemory.KogitoDevServiceTest.testDataIndexDevService</a></summary>
io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/PR_check___Build_projects___callbackStateTimeoutsExceeded/">PR check / Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/PR_check___Build_projects___callbackStateTimeoutsExceeded/">PR check / Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/MultipleTimerInstancesIT/PR_check___Build_projects___boundaryTimerEvent/">PR check / Build projects / org.kie.kogito.it.jobs.MultipleTimerInstancesIT.boundaryTimerEvent</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/MultipleTimerInstancesIT/PR_check___Build_projects___timerEvent/">PR check / Build projects / org.kie.kogito.it.jobs.MultipleTimerInstancesIT.timerEvent</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/MultipleTimerInstancesIT/PR_check___Build_projects___eventStateTimeouts/">PR check / Build projects / org.kie.kogito.it.jobs.MultipleTimerInstancesIT.eventStateTimeouts</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/ProcessAsyncIT/PR_check___Build_projects___testAsync/">PR check / Build projects / org.kie.kogito.it.jobs.ProcessAsyncIT.testAsync</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/PR_check___Build_projects___testDeleteTimerCycle/">PR check / Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testDeleteTimerCycle</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/PR_check___Build_projects___testBoundaryTimersOnTask/">PR check / Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testBoundaryTimersOnTask</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/PR_check___Build_projects___testTimerCycle/">PR check / Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testTimerCycle</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/PR_check___Build_projects___testTimers/">PR check / Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testTimers</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/PR_check___Build_projects___testDeleteBoundaryTimersOnTask/">PR check / Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testDeleteBoundaryTimersOnTask</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/ProcessTimerIT/PR_check___Build_projects___testCancelTimer/">PR check / Build projects / org.kie.kogito.it.jobs.ProcessTimerIT.testCancelTimer</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/SwitchStateTimeoutsIT/PR_check___Build_projects___switchStateEventConditionTimeoutsTransitionTimeoutsExceeded/">PR check / Build projects / org.kie.kogito.it.jobs.SwitchStateTimeoutsIT.switchStateEventConditionTimeoutsTransitionTimeoutsExceeded</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/WorkflowTimeoutsIT/PR_check___Build_projects___workflowTimeoutExceeded/">PR check / Build projects / org.kie.kogito.it.jobs.WorkflowTimeoutsIT.workflowTimeoutExceeded</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/HttpJobExecutionIT/executeJobWithStructuredModeEventsApi/">org.kie.kogito.it.jobs.HttpJobExecutionIT.executeJobWithStructuredModeEventsApi</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/HttpJobExecutionIT/deleteJobWithBinaryModeEventsApi/">org.kie.kogito.it.jobs.HttpJobExecutionIT.deleteJobWithBinaryModeEventsApi</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/HttpJobExecutionIT/deleteJobWithStructuredModeEventsApi/">org.kie.kogito.it.jobs.HttpJobExecutionIT.deleteJobWithStructuredModeEventsApi</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-apps-pr/job/PR-2249/1/testReport/org.kie.kogito.it.jobs/HttpJobExecutionIT/createAndExecuteJobWithBinaryModeEventsApi/">org.kie.kogito.it.jobs.HttpJobExecutionIT.createAndExecuteJobWithBinaryModeEventsApi</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:250)<br/> at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:255)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)<br/> at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)<br/> at java.base/java.lang.Thread.run(Thread.java:840)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:499)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image quay.io/keycloak/keycloak:26.1.3<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:421)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:364)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:447)<br/> at io.quarkus.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:200)<br/> ... 10 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)<br/> ... 15 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:556)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:909)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492)<br/> ... 18 more<br/>
</details>

**Review by ricardozanini — APPROVED** [review]

File: jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/vertx/VertxRouterSetupHelper.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+import io.vertx.ext.web.handler.FileSystemAccess;
+import io.vertx.ext.web.handler.LoggerHandler;
+import io.vertx.ext.web.handler.StaticHandler;
+import io.vertx.ext.web.handler.graphql.GraphiQLHandler;
+import io.vertx.ext.web.handler.graphql.GraphiQLHandlerOptions;
+
+public class VertxRouterSetupHelper {
+
+    public static final String UI_PATH_PROPERTY = "kogito.jobs-service.ui.path";
+    public static final String GRAPH_UI_PATH_PROPERTY = "kogito.jobs-service.vertx-graphql.ui.path";
```
Comment (wmedvede) [inline jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/vertx/VertxRouterSetupHelper.java]: The jobs service doesn't have graphql ui, also that  GRAPH_UI_PATH_PROPERTY constant is never used in the code.

UI_PATH_PROPERTY never used in the code.


I believe this PR might need an equivalent class to this:  https://github.com/apache/incubator-kie-kogito-apps/blob/ea4391f0092e5d42a20699474ed66642b85264f8/data-index/data-index-quarkus/data-index-service-quarkus-common/src/main/java/org/kie/kogito/index/vertx/QuarkusVertxRouterSetup.java

**Review by wmedvede — CHANGES_REQUESTED** [review]

File: jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/vertx/VertxRouterSetupHelper.java [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+
+    private VertxRouterSetupHelper() {
+    }
+
+    public static void setupRouter(Vertx vertx, Router router, String graphUIPath, String indexUIPath, boolean authEnabled, Function<RoutingContext, String> accessToken) {
+        router.route().handler(LoggerHandler.create());
+        GraphiQLHandler graphiQLHandler = GraphiQLHandler.create(vertx, new GraphiQLHandlerOptions().setEnabled(true));
```
Comment (wmedvede) [inline jobs-service/jobs-service-common/src/main/java/org/kie/kogito/jobs/service/vertx/VertxRouterSetupHelper.java]: Same comment, the JS doesn't have graphiql.

I think this PR should consider including only the landing page, IIRC plan html for the JS.

**Review by fantonangeli — APPROVED** [review]

**Review by wmedvede — APPROVED** [review]
